<script setup lang="ts">
import { computed } from 'vue'
import {
  LayoutDashboard,
  Star,
  Clock3,
  FolderLock,
  SlidersHorizontal,
  Settings,
  Plus,
  Search,
  X,
  ArrowUpRight,
  ArrowRight,
  KeyRound,
  Pencil,
  Trash2,
  LogOut,
  Menu,
  Moon,
  Sun,
  Monitor,
  Grid2X2,
  List,
  Pin,
  Globe,
  Package,
  Wallet,
  Boxes,
  Users,
  ShieldCheck,
  Terminal,
  Code,
  BookOpen,
  Compass,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  Eye,
  EyeOff,
  Copy,
  Check,
  Info,
  History,
  Download,
  MessageSquare,
  RefreshCw,
  LockKeyhole,
} from 'lucide-vue-next'
const props = defineProps<{ name: string; size?: number }>()
const icons: Record<string, typeof Globe> = {
  layout: LayoutDashboard,
  star: Star,
  clock: Clock3,
  'folder-lock': FolderLock,
  sliders: SlidersHorizontal,
  settings: Settings,
  plus: Plus,
  search: Search,
  x: X,
  external: ArrowUpRight,
  arrow: ArrowRight,
  key: KeyRound,
  edit: Pencil,
  trash: Trash2,
  logout: LogOut,
  menu: Menu,
  moon: Moon,
  sun: Sun,
  monitor: Monitor,
  grid: Grid2X2,
  list: List,
  pin: Pin,
  globe: Globe,
  package: Package,
  wallet: Wallet,
  boxes: Boxes,
  users: Users,
  shield: ShieldCheck,
  terminal: Terminal,
  code: Code,
  book: BookOpen,
  compass: Compass,
  down: ChevronDown,
  'chevron-right': ChevronRight,
  up: ChevronUp,
  eye: Eye,
  'eye-off': EyeOff,
  copy: Copy,
  check: Check,
  info: Info,
  history: History,
  download: Download,
  feedback: MessageSquare,
  refresh: RefreshCw,
  lock: LockKeyhole,
}
const component = computed(() => icons[props.name] || Globe)
</script>
<template>
  <component :is="component" class="icon" :size="size || 18" :stroke-width="1.7" aria-hidden="true" />
</template>
