"""independent_accounts_public_navigation_transfer"""

import uuid
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "9cbed07c5915"
down_revision: Union[str, None] = "2386764f6f0c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "site_settings",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("owner_user_id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "transfer_receipts",
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("package_id", sa.String(length=64), nullable=False),
        sa.Column("summary", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "package_id"),
    )
    with op.batch_alter_table("resources", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_public", sa.Boolean(), server_default="0" if op.get_bind().dialect.name == "sqlite" else sa.false(), nullable=False))

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("recovery_hash", sa.String(length=64), nullable=True))

    with op.batch_alter_table("workspaces", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("public_enabled", sa.Boolean(), server_default="0" if op.get_bind().dialect.name == "sqlite" else sa.false(), nullable=False)
        )
        batch_op.add_column(
            sa.Column(
                "collaboration_mode", sa.String(length=20), server_default="maintainers", nullable=False
            )
        )

    connection = op.get_bind()
    people = sa.table("users", sa.column("id", sa.String), sa.column("created_at", sa.DateTime))
    first_user = connection.scalar(sa.select(people.c.id).order_by(people.c.created_at).limit(1))
    if first_user:
        site = sa.table("site_settings", sa.column("id", sa.String), sa.column("owner_user_id", sa.String))
        connection.execute(site.insert().values(id="main", owner_user_id=first_user))
    _detach_personal_environments(connection, people)


def _detach_personal_environments(connection, people):
    """Keep personal endpoints independent of future department configuration."""
    envs = sa.table(
        "environments",
        *[
            sa.column(name, sa.String)
            for name in ("id", "scope", "workspace_id", "owner_user_id", "key", "label", "kind")
        ],
        sa.column("enabled", sa.Boolean),
        sa.column("sort_order", sa.Integer),
        sa.column("version", sa.Integer),
    )
    endpoints = sa.table(
        "endpoints",
        *[sa.column(name, sa.String) for name in ("id", "resource_id", "environment_id", "environment_key")],
    )
    resources = sa.table(
        "resources", *[sa.column(name, sa.String) for name in ("id", "scope", "owner_user_id")]
    )
    revisions = sa.table(
        "resource_revisions",
        sa.column("resource_id", sa.String),
        sa.column("version", sa.Integer),
        sa.column("snapshot", sa.JSON),
    )
    all_envs = {row["id"]: dict(row) for row in connection.execute(sa.select(envs)).mappings()}
    existing_keys = {}
    for row in all_envs.values():
        if row["owner_user_id"]:
            existing_keys.setdefault(row["owner_user_id"], set()).add(row["key"])
    copied, resource_maps = {}, {}
    rows = (
        connection.execute(
            sa.select(
                endpoints.c.id, endpoints.c.environment_id, endpoints.c.resource_id, resources.c.owner_user_id
            )
            .join(resources, resources.c.id == endpoints.c.resource_id)
            .where(resources.c.scope == "personal")
        )
        .mappings()
        .all()
    )
    for row in rows:
        original = all_envs.get(row["environment_id"])
        if not original or original["scope"] != "team":
            continue
        owner = row["owner_user_id"]
        pair = (owner, original["id"])
        if pair not in copied:
            keys = existing_keys.setdefault(owner, set())
            key = original["key"]
            if key in keys:
                key = key[:14] + "-m" + uuid.uuid4().hex[:6]
            keys.add(key)
            new_id = uuid.uuid4().hex
            connection.execute(
                envs.insert().values(
                    id=new_id,
                    scope="personal",
                    owner_user_id=owner,
                    workspace_id=None,
                    key=key,
                    label=original["label"],
                    kind=original["kind"],
                    enabled=original["enabled"],
                    sort_order=original["sort_order"],
                    version=1,
                )
            )
            copied[pair] = new_id
        new_id = copied[pair]
        connection.execute(
            endpoints.update()
            .where(endpoints.c.id == row["id"])
            .values(environment_id=new_id, environment_key=new_id)
        )
        resource_maps.setdefault(row["resource_id"], {})[original["id"]] = new_id
    for resource_id, environment_map in resource_maps.items():
        for row in (
            connection.execute(sa.select(revisions).where(revisions.c.resource_id == resource_id))
            .mappings()
            .all()
        ):
            snapshot = row["snapshot"]
            for endpoint in snapshot.get("endpoints", []):
                endpoint["environment_id"] = environment_map.get(
                    endpoint.get("environment_id"), endpoint.get("environment_id")
                )
            connection.execute(
                revisions.update()
                .where(revisions.c.resource_id == resource_id, revisions.c.version == row["version"])
                .values(snapshot=snapshot)
            )
    for owner in connection.scalars(sa.select(people.c.id)).all():
        keys = existing_keys.setdefault(owner, set())
        for order, (key, label) in enumerate((("dev", "开发"), ("test", "测试"), ("prod", "生产"))):
            if key not in keys:
                connection.execute(
                    envs.insert().values(
                        id=uuid.uuid4().hex,
                        scope="personal",
                        owner_user_id=owner,
                        workspace_id=None,
                        key=key,
                        label=label,
                        kind=key,
                        enabled=True,
                        sort_order=order,
                        version=1,
                    )
                )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workspaces", schema=None) as batch_op:
        batch_op.drop_column("collaboration_mode")
        batch_op.drop_column("public_enabled")

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("recovery_hash")

    with op.batch_alter_table("resources", schema=None) as batch_op:
        batch_op.drop_column("is_public")

    op.drop_table("transfer_receipts")
    op.drop_table("site_settings")
    # ### end Alembic commands ###
